yatube/about/urls.py
from django.urls import path
from . views import AboutAuthorView as Author, AboutTechView as Tech

app_name = 'about'

urlpatterns = [
    path('author/', Author.as_view(), name='author'),
    path('tech/', Tech.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
    path('new/', views.new_post, name='new_post'),
    path("follow/", views.follow_index, name="follow_index"),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/<int:post_id>/', views.post_view, name='post'),
    path('<str:username>/<int:post_id>/comment',
         views.add_comment, name='add_comment'),
    path('<str:username>/<int:post_id>/edit/',
         views.post_edit, name='post_edit'),
    path("<str:username>/follow/",
         views.profile_follow, name="profile_follow"),
    path("<str:username>/unfollow/",
         views.profile_unfollow, name="profile_unfollow"),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from django.contrib import admin
from django.urls import include, path


handler404 = 'posts.views.page_not_found'  # noqa
handler500 = 'posts.views.server_error'    # noqa

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

yatube/templates/includes/comments.html
<!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <form method="post">
      {% csrf_token %}
      <h5 class="card-header">Добавить комментарий:</h5>
      <div class="card-body">
        <div class="form-group">
             {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </div>
    </form>
  </div>
{% endif %}

<!-- Комментарии -->
{% for item in comments %}
  <div class="media card mb-4">
    <div class="media-body card-body">
      <h5 class="mt-0">
        <a
          href="{% url 'posts:profile' item.author.username %}"
          name="comment_{{ item.id }}"
        >{{ item.author.username }}</a>
      </h5>
        <p>{{ item.text|linebreaksbr }}</p>
    </div>
  </div>
{% endfor %}

yatube/templates/includes/footer.html
<!-- Шаблон footer.html -->
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p class="m-0 text-dark text-center ">
  <a href="{% url 'about:author' %}">Об авторе</a>
  <a href="{% url 'about:tech' %}">О технологиях</a>
    </p>
  <p class="m-0 text-dark text-center ">
  Социальная сеть <span style="color:red">Super</span>DuperFly © {{ year }}, все права защищены.
  </p>
</footer>

yatube/templates/includes/form.html
{% block form %}
<form method="post">
  {% csrf_token %}
  {% include 'includes/out_fields.html' %}

  <div class="col-md-6 offset-md-4">
    <button type="submit" class="btn btn-primary">
      {% block button %} {{submit}} {% endblock %}
    </button>
  </div>
</form>
{% endblock %}

yatube/templates/includes/menu.html
{% if user.is_authenticated %}
  <div class="row">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link {% if index %}active{% endif %}" href="{% url 'posts:index' %}">
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if follow %}active{% endif %}" href="{% url 'posts:follow_index' %}">
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}

yatube/templates/includes/nav.html
<nav class="navbar navbar-light" style="background-color: #64e5ff">
  <a class="navbar-brand" href="/"><span style="color:red">Super</span>DuperFly</a>
  <nav class="my-2 my-md-0 mr-md-3">
    {% if user.is_authenticated %}
      Пользователь: {{ user.username }}.
      <a class="p-2 text-dark" href="{% url 'posts:new_post' %}">Создать пост</a>
      {% if user.posts.count > 10 %}
        <a class="p-2 text-dark" href="{% url 'posts:new_post' %}">Создать сообщество</a>
      {% endif %}      
      <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
      <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
    {% else %}
      <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
      <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
    {% endif %}
  </nav>
</nav> 

yatube/templates/includes/out_error_fields.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger" role="alert">
        {{ field.label }}: {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
{% endif %}

yatube/templates/includes/out_fields.html
{% load user_filters %}
{% for field in form %}
  <div class="form-group row" aria-required={{ field.field.required }}>
    <label
      for="{{ field.id_for_label }}"
      class="col-md-4 col-form-label text-md-right">
      {{ field.label }}
      {% if field.field.required %}
        <span class="required">*</span>
      {% endif %}
    </label>
    <div class="col-md-6">
      {# подключаем фильтр и указываем класс #}
      {{ field|addclass:"form-control" }}
      {% if field.help_text %}
        <small
          id="{{ field.id_for_label }}-help"
          class="form-text text-muted">
          {{ field.help_text|safe }}
        </small>
      {% endif %}
    </div>
  </div>
{% endfor %}

yatube/templates/includes/paginator.html
{% if page.has_other_pages %}
  <nav>
    <ul class="pagination">
      {% if page.has_previous %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">&laquo; Предыдущая</span>
        </li>
      {% endif %}
      {% for i in page.paginator.page_range %}
        {% if page.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}
              <span class="sr-only">(текущая)</span>
            </span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page.has_next %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Следующая &raquo;</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

yatube/templates/includes/post_item.html
<div class="card mb-3 mt-1 shadow-sm">

  <!-- Отображение картинки -->
  {% load thumbnail %}
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img" src="{{ im.url }}">
  {% endthumbnail %}
  <!-- Отображение текста поста -->
  <div class="card-body">
    <p class="card-text">
      <!-- Ссылка на автора через @ -->
        <a name="post_{{ post.id }}" href="{% url 'posts:profile' post.author.username %}">
          <strong class="d-block text-gray-dark">@{{ post.author }}</strong>
        </a>
        {% if slice_not %}
          {{ post.text|linebreaks|urlize }}
        {% else %}
          {{ post.text|linebreaks|truncatewords:30|urlize }}
        {% endif %}
    </p>

    <!-- Если пост относится к какому-нибудь сообществу, то отобразим ссылку на него через # -->
    {% if group %}

    {% elif post.group %}
      <a class="card-link muted" href="{% url 'posts:group' post.group.slug %}">
        <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
      </a>
    {% endif %}

    <!-- Отображение ссылки на комментарии -->
    <div class="d-flex justify-content-between align-items-center">
      <div class="btn-group">
        {% if not slice_not %}
          <a class="btn btn-sm btn-primary" href="{% url 'posts:post' post.author.username post.id %}" role="button">
            Полный текст
          </a>
        {% endif %}
        <!-- Ссылка на редактирование поста для автора -->
        {% if slice_not and user == post.author %}
          <a class="btn btn-sm btn-info" href="{% url 'posts:post_edit' post.author.username post.id %}" role="button">
            Редактировать
          </a>
        {% endif %}
      </div>
      {% if post.comments.exists %}
        <div>
          Комментариев: {{ post.comments.count }}
        </div>
      {% endif %}

      <!-- Дата публикации поста -->
      <small class="text-muted">{{ post.pub_date|date }}</small>
    </div>
  </div>
</div>

yatube/templates/includes/user_card.html
<div class="card">
  <div class="card-body">
    <div class="h2">
      <!-- Имя автора -->
      {{ author.get_full_name }}
    </div>
    <div class="h3 text-muted">
      <!-- username автора -->
      @{{ author.username }}
    </div>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <div class="h6 text-muted">
        Подписчиков: {{ author.following.count }} <br>
        Подписан: {{ author.follower.count }}
      </div>
    </li>
    <li class="list-group-item">
      <div class="h6 text-muted">
        <!--Количество записей -->
        Записей: {{ page.paginator.count }}
      </div>
      {% if request.user != author %}
        <li class="list-group-item">
          {% if following %}
            <a
              class="btn btn-lg btn-light"
              href="{% url 'posts:profile_unfollow' author.username %}" role="button">
                Отписаться
            </a>
          {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button">
              Подписаться
            </a>
          {% endif %}
        </li>
      {% endif %}
    </li>
  </ul>
</div>